---
name: Publish coverage to CodeCov
on:
  workflow_call:
jobs:
  codecov:
    name: Upload to CodeCov.
    if: github.repository == 'aristanetworks/anta'
    runs-on: ubuntu-latest
    # These permissions are mandatory for OIDC to work
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Download coverage from unit tests
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: pytest-coverage
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload results to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          use_oidc: true
          fail_ci_if_error: true
