---
name: Publish coverage to CodeCov
on:
  workflow_run:
    workflows: ["Linting and Testing ANTA"]
    types: [completed]

jobs:
  codecov:
    name: Upload to CodeCov.
    if: github.repository == 'aristanetworks/anta'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Download coverage from unit tests
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: pytest-coverage
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          merge-multiple: true

      - name: Upload results to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
